<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\inex.Application\inex.Application.csproj" />
    <ProjectReference Include="..\inex.Data\inex.Data.csproj" />
  </ItemGroup>

</Project>
